### ISSUE TITLE
How to capture only multitouch gestures

### ISSUE THREAD

**Issue by heaversm** [expo/expo-multi-touch#1]
...also would love to be able to distinguish easily between single and multiple tap gestures

**Comment by heaversm** [comment]
I'm trying to wrap all of my component 'scenes' in a multitouch component so that, if a person performs a multitouch gesture at any point, this will trigger an app menu, and otherwise, the child views respond to the touch event. How do I accomplish this? It seems that the parent traps and stops propagation of all events - I would've expected those events to bubble upward from the innermost elements.

Ordinarily I would use a shake gesture, but I'm using expo, which reserves that gesture for itself.

**Comment by sjchmiela** [comment]
I don't know if this will fix your issue, but you may be happy to know that you can customize what gesture triggers Expo's developer menu. 🙂 If you go to `Profile` tab and tap `Options` button at the top right corner of the screen, you should be able to pick between `Shake gesture` and another gesture to trigger Expo menu.

**Comment by sjchmiela** [comment]
I’ll let myself close this issue due to inactivity, feel free to reopen it if you have any more questions!
